//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyDichVu
    {
        public int Id { get; set; }
        public string MaPhuHuynh { get; set; }
        public string NguoiThu { get; set; }
        public System.DateTime ThoiGianDK { get; set; }
        public int MaDichVu { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> ThoiGianThu { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual DichVu DichVu { get; set; }
        public virtual PhuHuynh PhuHuynh { get; set; }
    }
}
