//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemDanhHocSinh
    {
        public int Id { get; set; }
        public Nullable<int> Id_HocSinh { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public string NguoiDuaDon { get; set; }
        public string DenVe { get; set; }
        public string Id_NguoiDiemDanh { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual HocSinh HocSinh { get; set; }
    }
}
