//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemDanhGiaoVien
    {
        public int Id { get; set; }
        public string Id_GiaoVien { get; set; }
        public System.DateTime ThoiGian { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
    }
}
