//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocSinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HocSinh()
        {
            this.DiemDanhHocSinhs = new HashSet<DiemDanhHocSinh>();
            this.PhuHuynh_HocSinh = new HashSet<PhuHuynh_HocSinh>();
        }
    
        public int Id { get; set; }
        public string HoTen { get; set; }
        public string BiDanh { get; set; }
        public string DanToc { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string img { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string GioiTinh { get; set; }
        public int LopHoc { get; set; }
        public string TrangThai { get; set; }
        public string HKTT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemDanhHocSinh> DiemDanhHocSinhs { get; set; }
        public virtual Lop Lop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhuHuynh_HocSinh> PhuHuynh_HocSinh { get; set; }
    }
}
