//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TruongMamNonEntities : DbContext
    {
        public TruongMamNonEntities()
            : base("name=TruongMamNonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<C__MigrationHistory1> C__MigrationHistory1 { get; set; }
        public virtual DbSet<DangKyDichVu> DangKyDichVus { get; set; }
        public virtual DbSet<DichVu> DichVus { get; set; }
        public virtual DbSet<DiemDanhGiaoVien> DiemDanhGiaoViens { get; set; }
        public virtual DbSet<DiemDanhHocSinh> DiemDanhHocSinhs { get; set; }
        public virtual DbSet<GiaoVien_Lops> GiaoVien_Lops { get; set; }
        public virtual DbSet<GiaoVien> GiaoViens { get; set; }
        public virtual DbSet<HocSinh> HocSinhs { get; set; }
        public virtual DbSet<LoaiDV> LoaiDVs { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<NhomTuoi> NhomTuois { get; set; }
        public virtual DbSet<PhuHuynh_HocSinh> PhuHuynh_HocSinh { get; set; }
        public virtual DbSet<PhuHuynh> PhuHuynhs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThucDon> ThucDons { get; set; }
    }
}
